### ISSUE TITLE
Why put a lot of network computing on the CPU instead of the GPU?

### ISSUE THREAD

**Issue by AlephZr** [ShawK91/Evolutionary-Reinforcement-Learning#1]
In the old code, network computing (including forward propagation and backward propagation) is on the GPU. But in the new version of the parallelized code, except for the PG part, all network calculations (population, rollout) are on the CPU. Why is that?
Is it a compromise of parallelization, or am I misunderstanding the code?

**Comment by ShawK91** [comment]
This is correct. Most of the use-cases we observed/heard from the community involved projects where the compute resources available were of the nature NUM_CPUs >> NUM_GPUs. Thus we optimized for this resource scenario. Crucially, this enables the rollouts and policy gradient steps to run in parallel. The pg update runs in main (using data in the buffer up to the last generation) while concurrently, the other processes conduct rollouts and collect new data.

**Comment by AlephZr** [comment]
> This is correct. Most of the use-cases we observed/heard from the community involved projects where the compute resources available were of the nature NUM_CPUs >> NUM_GPUs. Thus we optimized for this resource scenario. Crucially, this enables the rollouts and policy gradient steps to run in parallel. The pg update runs in main (using data in the buffer up to the last generation) while concurrently, the other processes conduct rollouts and collect new data.

Thank you for your explanation. I have understood.
